name: test_site_deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.TEST_SSH_HOST }}
      - name: Rebuild docker images
        run: ssh root@${{ secrets.TEST_IP_ADDRESS }} "cd ~/client_api_service;
          doppler secrets -t ${{ secrets.TEST_DOPPLER_TOKEN }} download --no-file --format docker > .env;
          git pull origin develop;
          docker compose -f docker-compose-test.yml up -d --force-recreate --build --remove-orphans"
